# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pet_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PetWidget(object):
    def setupUi(self, PetWidget):
        PetWidget.setObjectName("PetWidget")
        PetWidget.resize(1200, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(PetWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.filterLabel = QtWidgets.QLabel(PetWidget)
        self.filterLabel.setObjectName("filterLabel")
        self.filterLayout.addWidget(self.filterLabel)
        self.customer_combo = QtWidgets.QComboBox(PetWidget)
        self.customer_combo.setObjectName("customer_combo")
        self.filterLayout.addWidget(self.customer_combo)
        self.txt_tim = QtWidgets.QLineEdit(PetWidget)
        self.txt_tim.setObjectName("txt_tim")
        self.filterLayout.addWidget(self.txt_tim)
        self.btn_timkiem = QtWidgets.QPushButton(PetWidget)
        self.btn_timkiem.setObjectName("btn_timkiem")
        self.filterLayout.addWidget(self.btn_timkiem)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.filterLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.filterLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.add_btn = QtWidgets.QPushButton(PetWidget)
        self.add_btn.setObjectName("add_btn")
        self.buttonLayout.addWidget(self.add_btn)
        self.edit_btn = QtWidgets.QPushButton(PetWidget)
        self.edit_btn.setObjectName("edit_btn")
        self.buttonLayout.addWidget(self.edit_btn)
        self.delete_btn = QtWidgets.QPushButton(PetWidget)
        self.delete_btn.setObjectName("delete_btn")
        self.buttonLayout.addWidget(self.delete_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.table = QtWidgets.QTableWidget(PetWidget)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.table, 1)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(PetWidget)
        QtCore.QMetaObject.connectSlotsByName(PetWidget)

    def retranslateUi(self, PetWidget):
        _translate = QtCore.QCoreApplication.translate
        PetWidget.setWindowTitle(_translate("PetWidget", "Quản Lý Thú Cưng"))
        self.filterLabel.setText(_translate("PetWidget", "Khách hàng:"))
        self.txt_tim.setPlaceholderText(_translate("PetWidget", "Tìm khách theo tên, số đt"))
        self.btn_timkiem.setText(_translate("PetWidget", "Tìm kiếm"))
        self.add_btn.setText(_translate("PetWidget", "➕ Thêm Thú Cưng"))
        self.edit_btn.setText(_translate("PetWidget", "✏️ Chỉnh Sửa"))
        self.delete_btn.setText(_translate("PetWidget", "🗑️ Xóa"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("PetWidget", "ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("PetWidget", "Tên"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("PetWidget", "Loài"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("PetWidget", "Tuổi"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("PetWidget", "Giống"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("PetWidget", "Ngày Tạo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PetWidget = QtWidgets.QWidget()
    ui = Ui_PetWidget()
    ui.setupUi(PetWidget)
    PetWidget.show()
    sys.exit(app.exec_())
